run:
  timeout: 120m

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - errorlint
    - copyloopvar
    - gofmt
    - goimports
    - gosec
    - gomodguard

linters-settings:
  gosec:
    excludes: []
    confidence: low
    config:
      global:
        audit: true

  gomodguard:
    blocked:
      modules:
        - "github.com/Azure/go-autorest/autorest/azure/auth":
            reason: "deprecated"

issues: {}

output:
  sort-results: true
